<template>
<!--    margin-left: -.5rem;margin-top: -.5rem;-->
    <div class="loading-small">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin-left: -.5rem;margin-top: -.5rem;background: none; display: block; shape-rendering: auto;" width="299px" height="299px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
            <g transform="rotate(0 50 50)">
                <rect x="47" y="22.5" rx="3" ry="3.9" width="6" height="15" fill="#a2a2a2">
                    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.9s" repeatCount="indefinite"></animate>
                </rect>
            </g><g transform="rotate(36 50 50)">
            <rect x="47" y="22.5" rx="3" ry="3.9" width="6" height="15" fill="#a2a2a2">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.8s" repeatCount="indefinite"></animate>
            </rect>
        </g><g transform="rotate(72 50 50)">
            <rect x="47" y="22.5" rx="3" ry="3.9" width="6" height="15" fill="#a2a2a2">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.7s" repeatCount="indefinite"></animate>
            </rect>
        </g><g transform="rotate(108 50 50)">
            <rect x="47" y="22.5" rx="3" ry="3.9" width="6" height="15" fill="#a2a2a2">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.6s" repeatCount="indefinite"></animate>
            </rect>
        </g><g transform="rotate(144 50 50)">
            <rect x="47" y="22.5" rx="3" ry="3.9" width="6" height="15" fill="#a2a2a2">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.5s" repeatCount="indefinite"></animate>
            </rect>
        </g><g transform="rotate(180 50 50)">
            <rect x="47" y="22.5" rx="3" ry="3.9" width="6" height="15" fill="#a2a2a2">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.4s" repeatCount="indefinite"></animate>
            </rect>
        </g><g transform="rotate(216 50 50)">
            <rect x="47" y="22.5" rx="3" ry="3.9" width="6" height="15" fill="#a2a2a2">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.3s" repeatCount="indefinite"></animate>
            </rect>
        </g><g transform="rotate(252 50 50)">
            <rect x="47" y="22.5" rx="3" ry="3.9" width="6" height="15" fill="#a2a2a2">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.2s" repeatCount="indefinite"></animate>
            </rect>
        </g><g transform="rotate(288 50 50)">
            <rect x="47" y="22.5" rx="3" ry="3.9" width="6" height="15" fill="#a2a2a2">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.1s" repeatCount="indefinite"></animate>
            </rect>
        </g><g transform="rotate(324 50 50)">
            <rect x="47" y="22.5" rx="3" ry="3.9" width="6" height="15" fill="#a2a2a2">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="0s" repeatCount="indefinite"></animate>
            </rect>
        </g>
            <!-- [ldio] generated by https://loading.io/ --></svg>
    </div>

</template>

<script>

export default {
    name: "Small",
    data(){
        return {

        }
    }
}
</script>

<style scoped lang="scss">
.loading-small{
    height: 3rem;
    width: 3rem;
    svg{
        height: 4rem;
        width: 4rem;
    }
}
</style>